import { useUser } from "@clerk/nextjs";
import { type Listing } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import Link from "next/link";
import Image from "next/image";
import { useForm, SubmitHandler } from "react-hook-form";
<script src="https://unpkg.com/flowbite@1.4.4/dist/flowbite.js"></script>

export default function ListingView() {
  const router = useRouter();
  const { register, handleSubmit, reset } = useForm<{message: string}>();

  const listing = api.listings.get.useQuery(
    {
      listingId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );
  const user = useUser();

  const sendMessage = api.listings.sendMessage.useMutation();

  const listingItem = listing.data;

  if (!listingItem) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Ver Publicación</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/dales.png" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.css" rel="stylesheet" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-800">
        <div className="container mx-auto flex flex-col gap-12">
          <h1 className="mt-12 text-4xl">{listingItem.name}</h1>
          <div className="relative h-96 w-full">
            <Image className="object-cover" src="/casa1.jpg" alt="" fill />
          </div>
          <p>{listingItem.description}</p>
          <p>$ {listingItem.price}</p>

        {user.isSignedIn && (
          <form
            className="flex flex-col gap-4"
            onSubmit={handleSubmit((formData) => {
              sendMessage.mutateAsync({
                message: formData.message,
                listingId: listingItem.id,
              })
              .then(() => {
                reset();
              });
            })}
          >
            <div>
              <label
                htmlFor="name"
                className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
              >
                Mensaje
              </label>
              <textarea
                id="name"
                className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                {...register("message", { required: true })}
              />
            </div>
            <button className="inline-flex items-center rounded-lg bg-blue-700 px-3 py-2 text-center text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Enviar Mensaje
            </button>
          </form>
        )}
        </div>
      </main>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.js"></script>
    </>
  );
}
