import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
<script src="https://unpkg.com/flowbite@1.4.4/dist/flowbite.js"></script>

export default function Posts() {
  const messages = api.listings.getMessage.useQuery();

  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/dales.png" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.css" rel="stylesheet" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-800">
        <div className="container mx-auto">
          <h1 className="mb-8 mt-12 pl-4 text-4xl">Tus Posts</h1>

          <div className="relative mb-16 overflow-x-auto">
            <table className="w-full text-left text-sm text-gray-500 dark:text-gray-400">
              <thead className="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                  <th scope="col" className="px-6 py-3">
                    De
                  </th>
                  <th scope="col" className="px-6 py-3">
                    Mensaje
                  </th>
                </tr>
              </thead>
              <tbody>
                {messages?.data?.map((message) => (
                  <tr
                    key={message.id}
                    className="border-b bg-white dark:border-gray-700 dark:bg-gray-800"
                  >
                    <td className="px-6 py-4">{message.fromUserName}</td>
                    <td className="px-6 py-4">{message.message}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.js"></script>
    </>
  );
}
