import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useForm, SubmitHandler } from "react-hook-form";
import { useRouter } from "next/router";
import Image from "next/image";
<script src="https://unpkg.com/flowbite@1.4.4/dist/flowbite.js"></script>;

type SellItemForm = {
  name: string;
  description: string;
  price: string;
};

export default function VenderProducto() {
  const createListing = api.listings.create.useMutation();
  const router = useRouter();
  const { register, handleSubmit } = useForm<SellItemForm>();

  const onSubmit = (formData: SellItemForm) => {
    createListing
      .mutateAsync({
        ...formData,
        price: parseFloat(formData.price),
      })
      .then(() => {
        router.push("/");
      });
  };
  return (
    <>
      <Head>
        <title>Vender un Producto</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/dales.png" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-12 bg-gray-800">
        <div className="container max-w-5xl">
          <h1 className="mb-8 mt-12 pl-4 text-4xl">Vender un Producto</h1>
          <form
            className="flex flex-col gap-4"
            onSubmit={handleSubmit(onSubmit)}
          >
            <div>
              <label
                htmlFor="name"
                className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
              >
                Nombre del Producto
              </label>
              <input
                id="name"
                className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                {...register("name", { required: true })}
              />
            </div>

            <div>
              <label
                htmlFor="description"
                className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
              >
                Descripción
              </label>
              <textarea
                id="description"
                className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                {...register("description", { required: true })}
              />
            </div>

            <div>
              <label
                htmlFor="price"
                className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
              >
                Precio
              </label>
              <input
                id="price"
                className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                type="number"
                {...register("price", { required: true })}
              />
            </div>
            <button
              type="submit"
              className="mb-2 mr-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
            >
              Publicar
            </button>
          </form>
          <div className="relative mt-12 h-96 w-full">
            <Image className="object-cover" src="/casa1.jpg" alt="" fill />
          </div>
        </div>
      </main>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.6/flowbite.min.js"></script>
    </>
  );
}
